### ISSUE TITLE
Add .call_async to BaseOperation

### ISSUE THREAD

**Issue by OrestF** [OrestF/readymade#4]

**Comment by Misha7776** [comment]
@OrestF
BaseJob class:
```
class BaseJob < ApplicationJob
  def perform(service_klass, *args)
    service_klass.constantize.call(*args)
  end
end
```
Usage:
`BaseJob.set(queue: :critical).perform_async('Users::Action::SendNotification', record: user)`
As a suggestion for this issue.

**Comment by dmrAnderson** [comment]
@OrestF 
What is the current state of this issue?
🤔

**Comment by OrestF** [comment]
Done
